title: PReviewer

# List of PR reviewers
reviewers: [akasrai]

# PR title regex
prtitle:
  regex: '[a-zA-Z]'
  example: 'This is the PR title example'

# Checklist validation
checklists: [
    'Tested on local machine',
    'My code follows the style guidelines of this project',
    'I have performed a self-review of my own code',
    'My changes generate no new warnings',
    # The first string before | is title and others are options when checklists are grouped and min of one checklist is to be checked
    'Type of Change|Bug fix|New feature|Improvement|Breaking change',
    'Platform|Backend|Frontend',
  ]
